require 'rake/clean'
require 'rubygems'
require 'rubygems/package_task'
require 'rdoc/task'
require 'cucumber'
require 'cucumber/rake/task'

########################################################################
# Definition des taches
########################################################################
task :default => [:run]

task :tests => [:acceptation_tests, :tests_unitaires]

task :tests_unitaires => [:test_etudiant, 
                          :test_cours,                           
                          :test_accesseur,
                          :test_format,
                          :test_bdCours,]

task :acceptation_tests => [:acceptation_liste,
                            :acceptation_ajout]

task :run do
  sh %{bundle exec bin/bde}
end
########################################################################


########################################################################
# Test Unitaire
########################################################################
task :test_etudiant do
  sh %{rake test TEST=test/test_etudiant}
end

task :test_cours do
  sh %{rake test TEST=test/test_cours}
end

task :test_bdCours do
  sh %{rake test TEST=test/test_baseDonneeCours}
end

task :test_accesseur do
  sh %{rake test TEST=test/test_accesseur}
end

task :test_format do
  sh %{rake test TEST=test/test_format}
end
########################################################################


########################################################################
# Test Acceptation
########################################################################
task :acceptation_liste do
  sh %{rake test_acceptation TEST=test_acceptation/liste_test.rb}
end
task :acceptation_ajout do
  sh %{rake test_acceptation TEST=test_acceptation/ajout_test.rb}
end
########################################################################


########################################################################
Rake::RDocTask.new do |rd|
  rd.main = "README.rdoc"
  rd.rdoc_files.include("README.rdoc","lib/**/*.rb","bin/**/*")
  rd.title = 'Your application title'
end

spec = eval(File.read('bde.gemspec'))

Gem::PackageTask.new(spec) do |pkg|
end
CUKE_RESULTS = 'results.html'
CLEAN << CUKE_RESULTS
desc 'Run features'
Cucumber::Rake::Task.new(:features) do |t|
  opts = "features --format html -o #{CUKE_RESULTS} --format progress -x"
  opts += " --tags #{ENV['TAGS']}" if ENV['TAGS']
  t.cucumber_opts =  opts
  t.fork = false
end

desc 'Run features tagged as work-in-progress (@wip)'
Cucumber::Rake::Task.new('features:wip') do |t|
  tag_opts = ' --tags ~@pending'
  tag_opts = ' --tags @wip'
  t.cucumber_opts = "features --format html -o #{CUKE_RESULTS} --format pretty -x -s#{tag_opts}"
  t.fork = false
end

task :cucumber => :features
task 'cucumber:wip' => 'features:wip'
task :wip => 'features:wip'

require 'rake/testtask'
Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.test_files = FileList['test/*_test.rb']
end

Rake::TestTask.new(:test_acceptation) do |t|
  t.libs << "test_acceptation"
  t.test_files = FileList['test_acceptation/*_test.rb']
end
########################################################################
